CREATE SEQUENCE O360SEQNO
   INCREMENT    1
   START        1
   MAXVALUE     9999999999
   MINVALUE     1
   CYCLE
;

CREATE OR REPLACE FUNCTION GETO360DAOSEQNO(VARCHAR)
RETURNS BIGINT AS '
DECLARE
    iO360SeqNo BIGINT;
BEGIN
    SELECT NEXTVAL(''O360SEQNO'') INTO iO360SeqNo;
    RETURN iO360SeqNo;
END;
' LANGUAGE 'plpgsql';

CREATE TABLE Cur_Flow_Search(
    O360Seq       VARCHAR(20)    NOT NULL,
    Flow_ID       VARCHAR(20)    NOT NULL,
    Flow_Order    VARCHAR(3)     NOT NULL,
    User_Key      VARCHAR(50)    NOT NULL,
    CONSTRAINT PK32 PRIMARY KEY (Flow_ID,Flow_Order,User_Key)
);

CREATE TABLE Cur_Flow_Sync(
    O360Seq            VARCHAR(20)    NOT NULL,
    Flow_ID            VARCHAR(20)     NOT NULL,
    Flow_Order         VARCHAR(3)     NOT NULL,
    O360ErrCode        VARCHAR(5)     DEFAULT '00000' NOT NULL,
    Join_O360Seq       VARCHAR(20),
    Join_Flow_ID       VARCHAR(20),
    Join_Flow_Order    VARCHAR(3),
    Join_Cmd_ID        VARCHAR(2),
    CONSTRAINT PK19 PRIMARY KEY (O360Seq,Flow_ID,Flow_Order)
);

CREATE TABLE TR_STORE(
    STORE_ID      VARCHAR(40) not null,
    STORE_ORDER   VARCHAR(8),
    STORE_DATE    VARCHAR(8),
    STROR_TIME    VARCHAR(6),
    RETRIEVE_FLAG VARCHAR(1),
    CTF_CONTEXT    BYTEA
);

CREATE INDEX TR_STORE_IDX ON TR_STORE(STORE_ID);

CREATE OR REPLACE FUNCTION GETO360DAOSEQNO(VARCHAR)
RETURNS BIGINT AS '
DECLARE
    iO360SeqNo BIGINT;
BEGIN
    SELECT NEXTVAL(''O360SEQNO'') INTO iO360SeqNo;
    RETURN iO360SeqNo;
END;
' LANGUAGE 'plpgsql';


CREATE TABLE SERVERINFO(
    SERVERID    VARCHAR(15)    NOT NULL,
    MQ          CHAR(2),
    DB          CHAR(2),
    ST          CHAR(2),
    CONSTRAINT SYS_C002688 PRIMARY KEY (SERVERID)
) 
;

CREATE TABLE SERVER_GROUP (
    SERVERID    VARCHAR(15)    NOT NULL,
    GROUPID     VARCHAR(15)    NOT NULL,
    PRIMARY KEY (SERVERID)
)
;

CREATE TABLE MQPORTINFO(
    PORT    VARCHAR(5)    NOT NULL,
    CONSTRAINT SYS_C002690 PRIMARY KEY (PORT)
) 
;
CREATE TABLE CHANNEL_ID(
    CHANNEL_ID      CHAR(4)      NOT NULL,
    CODE_TYPE       CHAR(1)      DEFAULT 'A' NOT NULL,
    CHANNEL_DESC    CHAR(254),
    PRIMARY KEY (CHANNEL_ID)
) 
;
CREATE TABLE COMM_COMMON(
    TERM_ID               CHAR(16)         NOT NULL,
    IsAct                 CHAR(1)          DEFAULT 'N' NOT NULL,
    PORT                  VARCHAR(5)      NOT NULL,
    CHANNEL_ID            CHAR(4)          NOT NULL,
    CHANNEL_OUT_QTYPE     DECIMAL(31, 0)    NOT NULL,
    CHANNEL_OUT_QENTRY    CHAR(4)          NOT NULL,
    CHANNEL_IN_QTYPE      DECIMAL(31, 0)    DEFAULT 100 NOT NULL,
    CHANNEL_IN_QENTRY     CHAR(4)          NOT NULL,
    LOGICAL_GROUP_ID      CHAR(16),
    PHYSICAL_GROUP_ID     CHAR(8)          NOT NULL,
    PROTOCOLTYPE          CHAR(10),
    GWY_MODE              CHAR(20),
    MQSERVER              CHAR(15),
    TERM_DESC             CHAR(254),
    LOG_LEVEL           CHAR(2)     DEFAULT ' 2'   NOT NULL,
    PRIMARY KEY (TERM_ID)
) 
;


CREATE TABLE COMM_SNA(
    TERM_ID        CHAR(16)    NOT NULL,
    DRIVER_NAME    CHAR(14),
    LUADDR         CHAR(3)     NOT NULL,
    CHANGED        CHAR(1)     DEFAULT 'N' NOT NULL,
    LU_TYPE        CHAR(2)     NOT NULL,
    MODE_NAME      CHAR(20),
    ROLE           CHAR(1)     NOT NULL,
    SYNC_MODE      CHAR(20),
    ISTATE         CHAR(1)     NOT NULL,
    SYNC_CHOQTYPE  VARCHAR(38),
    PRIMARY KEY (TERM_ID)
) 
;

CREATE TABLE COMM_SNALU62C(
    TERM_ID       CHAR(16)        NOT NULL,
    SERVERID      VARCHAR(15)    NOT NULL,
    CHANGED       CHAR(1)         DEFAULT 'N' NOT NULL,
    ROLE          CHAR(1)         NOT NULL,
    SYNC_MODE     CHAR(20),
    ISTATE        CHAR(1)         NOT NULL,
    SIDE_INFO     CHAR(8)         NOT NULL,
    RTPN          CHAR(14)         NOT NULL,
    PLU           CHAR(17)        NOT NULL,
    MODE_NAME     CHAR(8),
    USERNAME      CHAR(14),
    PASSWORD      CHAR(14),
    SYNC_CHOQTYPE VARCHAR(38),
    PRIMARY KEY (TERM_ID)
) 
;

CREATE TABLE COMM_SNALU62L(
    TERM_ID      CHAR(16)    NOT NULL,
    SERVERID     VARCHAR(15)    NOT NULL,
    CHANGED      CHAR(1)     DEFAULT 'N' NOT NULL,
    TPN          CHAR(8)     NOT NULL,
    ROLE         CHAR(1)     NOT NULL,
    SYNC_MODE    CHAR(20),
    ISTATE       CHAR(1)     NOT NULL,
    PRIMARY KEY (TERM_ID)
) 
;
CREATE TABLE COMM_TCP(
    TERM_ID       CHAR(16)        NOT NULL,
    SERVERID      VARCHAR(15)    NOT NULL,
    IPADDR        CHAR(15)        NOT NULL,
    PORT          CHAR(5)         NOT NULL,
    MODE_NAME     CHAR(20),
    ROLE          CHAR(1)         NOT NULL,
    SYNC_MODE     CHAR(20),
    ISTATE        CHAR(1)         NOT NULL,
    CAFILE        VARCHAR(36),
    CERTFILE      VARCHAR(36),
    PEMPASS       VARCHAR(36),
    TCPOPTIONS    VARCHAR(15),
    SYNC_CHOQTYPE VARCHAR(38),
    TCPOPTION_MODE CHAR(20),
    PRIMARY KEY (TERM_ID)
) 
;

CREATE TABLE COMM_X25(
    TERM_ID       CHAR(16)        NOT NULL,
    SERVERID      VARCHAR(15)    NOT NULL,
    LINKNAME      CHAR(10)        NOT NULL,
    CHANNELNUM    CHAR(2)         NOT NULL,
    CONMODE       CHAR(1)         NOT NULL,
    ROLE          CHAR(1)         NOT NULL,
    SYNC_MODE     CHAR(20),
    ISTATE        CHAR(1)         NOT NULL,
    PRIMARY KEY (TERM_ID)
) 
;

CREATE TABLE COMM_MQGWY(
    TERM_ID         CHAR(16)        NOT NULL,
    SERVERID        VARCHAR(15)     NOT NULL,
    CONN_NAME       CHAR(48)        NOT NULL,
    QUEUE_MANAGER   VARCHAR(48)     NOT NULL,
    MODE_NAME       CHAR(20),
    CHANNEL         VARCHAR(20)     DEFAULT 'SYSTEM.DEF.SVRCONN'  NOT NULL,
    CIPHERSPEC      VARCHAR(32),
    CIPHERSPECKEY   VARCHAR(20),
    IN_QENTRY       VARCHAR(120)    NOT NULL,
    OUT_QENTRY      VARCHAR(120)    NOT NULL,
    CCSID           CHAR(4)         DEFAULT '819' NOT NULL,
    ROLE            CHAR(1)         DEFAULT 'M'   NOT NULL,
    SYNC_MODE       CHAR(20),
    SYNC_CHOQTYPE   VARCHAR(38),
    ISTATE          CHAR(1)         NOT NULL,
    PRIMARY KEY (TERM_ID)
)
;

CREATE TABLE COMM_FISCTCP(
    TERM_ID      CHAR(16)        NOT NULL,
    SERVERID     VARCHAR(15)    NOT NULL,
    IPADDR       CHAR(15)        NOT NULL,
    PORT         CHAR(7)         NOT NULL,
    ROLE         CHAR(1)         NOT NULL,
    CLIENTID     CHAR(8)         NOT NULL,
    RACF_PW      CHAR(8)         NOT NULL,
    ISTATE       CHAR(1)         NOT NULL,
    TIMEOUT      DECIMAL(3)      DEFAULT 0,
    PRIMARY KEY (TERM_ID)
) 
;

CREATE TABLE GWY_MODE
(
  MODE_NAME      CHAR(20)                       NOT NULL,
  MODE_PROTOCOL  CHAR(1)                        NOT NULL,
  MODE_CONTENT   CHAR(254)                      NOT NULL,
  MODE_DESC      CHAR(254),
  PRIMARY KEY (MODE_NAME,MODE_PROTOCOL)
)
;

CREATE TABLE GWY_MODE_EXT
(
  MODE_NAME      CHAR(254)                       NOT NULL,
  MODE_PROTOCOL  CHAR(1)                        NOT NULL,
  MODE_CONTENT   CHAR(254)                      NOT NULL,
  MODE_DESC      CHAR(254),
  PRIMARY KEY (MODE_NAME,MODE_PROTOCOL)
)
;

CREATE TABLE SNA_LU(
    DRIVER_NAME    CHAR(14)    NOT NULL,
    LUADDR         CHAR(3)    NOT NULL,
    NOTIFY         CHAR(4),
    TYPE           CHAR(4),
    LOG            CHAR(5),
    PRIMARY KEY (DRIVER_NAME,LUADDR)
) 
;


CREATE TABLE SNA_MODE(
    MODE_NAME    CHAR(8)          NOT NULL,
    MAXSESS      DECIMAL(31, 0)    DEFAULT 8,
    MINCWIN      DECIMAL(31, 0)    DEFAULT 4,
    RECPACE      DECIMAL(31, 0)    DEFAULT 4,
    MAXRUSIZE    DECIMAL(31, 0)    DEFAULT 0,
    PRIMARY KEY (MODE_NAME)
) 
;


CREATE TABLE SNA_PU(
    DRIVER_NAME    CHAR(14)         NOT NULL,
    IsAct          CHAR(1)         DEFAULT 'N' NOT NULL,
    SERVERID       VARCHAR(15)    NOT NULL,
    CHANGED        CHAR(1)         DEFAULT 'N' NOT NULL,
    DLCTYPE        CHAR(8)         NOT NULL,
    PUTYPE         CHAR(8)         NOT NULL,
    DEVICE         CHAR(8)         NOT NULL,
    LCLSAP         CHAR(2),
    RMTSAP         CHAR(2),
    XID            CHAR(8),
    CPNAME         CHAR(17),
    LCLNAME        CHAR(8),
    LINKNAME       CHAR(8),
    CALLTYPE       CHAR(6),
    RMTADDR        CHAR(12),
    LCLADDR        CHAR(12),
    IFRAME         CHAR(4),
    RWINDOW        CHAR(3),
    TWINDOW        CHAR(3),
    LINERETRY      CHAR(2),
    TIMEOUT        CHAR(2),
    BUFCNT         CHAR(5),
    LOG            CHAR(5),
    LEASED       CHAR(3),
    STNADDR    CHAR(3),
    ENCODING      CHAR(4),
    PHYSLINK        CHAR(10),
    DEFAULTMODE      CHAR(8),
    PRIMARY KEY (DRIVER_NAME)
) 
;

CREATE TABLE COMM_WS(
    TERM_ID       CHAR(16)        NOT NULL,
    SERVERID      VARCHAR(15)     NOT NULL,
    URL           VARCHAR(80)     NOT NULL,
    ROLE          CHAR(1)         NOT NULL,
    SYNC_MODE     CHAR(20)        NOT NULL,
    SYNC_CHOQTYPE VARCHAR(38)     NOT NULL,
    CHANNEL_IN_ID CHAR(4)         NOT NULL,
    ENCODING      CHAR(15)        NOT NULL, 
    CAFILE        VARCHAR(36),
    CERTFILE      VARCHAR(36),
    PEMPASS       VARCHAR(36),
    ISMUTUALAUTH  VARCHAR(5),
    PRIMARY KEY (TERM_ID)
) 
;

CREATE TABLE COMM_ICON (
    TERM_ID      CHAR(16)        NOT NULL,
    SERVERID     VARCHAR(15)     NOT NULL,
    IPADDR       CHAR(15)        NOT NULL,
    PORT         CHAR(7)         NOT NULL,
    ICON_OPTION  CHAR(2),
    IRM_ID       CHAR(8)         NOT NULL,
    IRM_CLIENTID CHAR(8)         NOT NULL,
    CHECKCODE    CHAR(8)         NOT NULL,
    ROLE         CHAR(1)         NOT NULL,
    TIMEOUT      CHAR(3),
    MODE_NAME    CHAR(20),
    ISTATE       CHAR(1)         NOT NULL,
    PRIMARY KEY (TERM_ID)
)
;


ALTER TABLE COMM_COMMON ADD CONSTRAINT RefCHANNEL_ID39 
    FOREIGN KEY (CHANNEL_ID)
    REFERENCES CHANNEL_ID(CHANNEL_ID)
;

ALTER TABLE COMM_COMMON ADD CONSTRAINT RefMQPORTINFO40 
    FOREIGN KEY (PORT)
    REFERENCES MQPORTINFO(PORT)
;

ALTER TABLE COMM_SNA ADD CONSTRAINT RefCOMM_COMMON19 
    FOREIGN KEY (TERM_ID)
    REFERENCES COMM_COMMON(TERM_ID)
;

ALTER TABLE COMM_SNA ADD CONSTRAINT RefSNA_LU44 
    FOREIGN KEY (DRIVER_NAME,LUADDR)
    REFERENCES SNA_LU(DRIVER_NAME,LUADDR)
;


ALTER TABLE COMM_SNALU62C ADD CONSTRAINT RefCOMM_COMMON33 
    FOREIGN KEY (TERM_ID)
    REFERENCES COMM_COMMON(TERM_ID)
;

ALTER TABLE COMM_SNALU62C ADD CONSTRAINT RefSNA_MODE34 
    FOREIGN KEY (MODE_NAME)
    REFERENCES SNA_MODE(MODE_NAME)
;

ALTER TABLE COMM_SNALU62C ADD CONSTRAINT RefSERVERINFO35 
    FOREIGN KEY (SERVERID)
    REFERENCES SERVERINFO(SERVERID)
;
ALTER TABLE COMM_SNALU62L ADD CONSTRAINT RefCOMM_COMMON25 
    FOREIGN KEY (TERM_ID)
    REFERENCES COMM_COMMON(TERM_ID)
;

ALTER TABLE COMM_SNALU62L ADD CONSTRAINT RefSERVERINFO39 
    FOREIGN KEY (SERVERID)
    REFERENCES SERVERINFO(SERVERID)
;

ALTER TABLE COMM_TCP ADD CONSTRAINT RefCOMM_COMMON26 
    FOREIGN KEY (TERM_ID)
    REFERENCES COMM_COMMON(TERM_ID)
;

ALTER TABLE COMM_TCP ADD CONSTRAINT RefSERVERINFO36 
    FOREIGN KEY (SERVERID)
    REFERENCES SERVERINFO(SERVERID)
;

ALTER TABLE COMM_X25 ADD CONSTRAINT RefCOMM_COMMON27 
    FOREIGN KEY (TERM_ID)
    REFERENCES COMM_COMMON(TERM_ID)
;

ALTER TABLE COMM_X25 ADD CONSTRAINT RefSERVERINFO37 
    FOREIGN KEY (SERVERID)
    REFERENCES SERVERINFO(SERVERID)
;


ALTER TABLE COMM_MQGWY ADD CONSTRAINT RefCOMM_COMMON28
    FOREIGN KEY (TERM_ID)
    REFERENCES COMM_COMMON(TERM_ID)
;

ALTER TABLE COMM_MQGWY ADD CONSTRAINT RefSERVERINFO40
    FOREIGN KEY (SERVERID)
    REFERENCES SERVERINFO(SERVERID)
;

ALTER TABLE COMM_FISCTCP ADD CONSTRAINT RefCOMM_COMMON29
    FOREIGN KEY (TERM_ID)
    REFERENCES COMM_COMMON(TERM_ID)
;

ALTER TABLE COMM_FISCTCP ADD CONSTRAINT RefSERVERINFO41
    FOREIGN KEY (SERVERID)
    REFERENCES SERVERINFO(SERVERID)
;

ALTER TABLE SNA_LU ADD CONSTRAINT RefSNA_PU10 
    FOREIGN KEY (DRIVER_NAME)
    REFERENCES SNA_PU(DRIVER_NAME)
;

ALTER TABLE SNA_PU ADD CONSTRAINT RefSERVERINFO38 
    FOREIGN KEY (SERVERID)
    REFERENCES SERVERINFO(SERVERID)
;

ALTER TABLE COMM_WS ADD CONSTRAINT RefCOMM_COMMON34
    FOREIGN KEY (TERM_ID)
    REFERENCES COMM_COMMON(TERM_ID)
;

ALTER TABLE COMM_WS ADD CONSTRAINT RefSERVERINFO42
    FOREIGN KEY (SERVERID)
    REFERENCES SERVERINFO(SERVERID)
;

ALTER TABLE COMM_ICON ADD CONSTRAINT RefCOMM_COMMON35
    FOREIGN KEY (TERM_ID)
    REFERENCES COMM_COMMON(TERM_ID)
;

ALTER TABLE COMM_ICON ADD CONSTRAINT RefSERVERINFO43
    FOREIGN KEY (SERVERID)
    REFERENCES SERVERINFO(SERVERID)
;



CREATE TABLE ATMCMDLOGA (
O360TXNSEQNO CHAR(20) NOT NULL,
O360SYSDATE CHAR(8) NOT NULL,
O360SYSTIME CHAR(6) NOT NULL,
HOSTNAME CHAR(36) NOT NULL,
CHANNEL CHAR(4) NOT NULL,
O360WSID CHAR(16),
UUID CHAR(36),
TERMID CHAR(8) NOT NULL,
ATMCTLCMD CHAR(3),
O360RESULTCODE CHAR(4)
) ;



CREATE TABLE ATMCMDLOGB (
O360TXNSEQNO CHAR(20) NOT NULL,
O360SYSDATE CHAR(8) NOT NULL,
O360SYSTIME CHAR(6) NOT NULL,
HOSTNAME CHAR(36) NOT NULL,
CHANNEL CHAR(4) NOT NULL,
O360WSID CHAR(16),
UUID CHAR(36),
TERMID CHAR(8) NOT NULL,
ATMCTLCMD CHAR(3),
O360RESULTCODE CHAR(4)
) ;


CREATE TABLE ATMCMDLOGH (
O360TXNSEQNO CHAR(20) NOT NULL,
O360SYSDATE CHAR(8) NOT NULL,
O360SYSTIME CHAR(6) NOT NULL,
HOSTNAME CHAR(36) NOT NULL,
CHANNEL CHAR(4) NOT NULL,
O360WSID CHAR(16),
UUID CHAR(36),
TERMID CHAR(8) NOT NULL,
ATMCTLCMD CHAR(3),
O360RESULTCODE CHAR(4)
) ;



CREATE TABLE ATMCTL (
TERMID CHAR(8) NOT NULL,
ATM_NO CHAR(4) NOT NULL,
BRNO CHAR(4) NOT NULL,
SADDR CHAR(40) NOT NULL,
SCODE CHAR(1),
PADDR CHAR(2),
NCR CHAR(4),
KEYCHG_FLAG CHAR(1),
KEYNO CHAR(5),
PORT CHAR(4) NOT NULL,
FEP CHAR(1),
TYPE CHAR(4) NOT NULL,
ADDR CHAR(320) NOT NULL,
NAME CHAR(16),
TEL CHAR(14),
AREA CHAR(1),
KIND CHAR(1),
PII_GROUP CHAR(1),
CHANNEL_CODE CHAR(1),
COUNTY_CODE CHAR(1),
A_CODE CHAR(1),
NET_CODE CHAR(1),
FEPSERVER CHAR(5),
FEPTCPPORT CHAR(5),
O360WSID CHAR(16),
ATMVERSION CHAR(16),
SSLVERSION CHAR(7),
CONNLISTVERSION CHAR(16),
IREQ_CODE CHAR(1),
SREQ_CODE CHAR(1),
BRANCH_NAME CHAR(25),
CITY CHAR(13),
ADDR_ENG CHAR(300) NOT NULL,
GRP CHAR(10) NOT NULL,
MONITOR_NODE CHAR(2) NOT NULL,
STARTDATETIME CHAR(14) NOT NULL,
INSTALLDATETIME CHAR(14) NOT NULL,
ATMIP CHAR(15) NOT NULL,
DVRIP CHAR(15) NOT NULL,
OTHIP CHAR(15),
TYPE_DMS CHAR(10) NOT NULL,
OPDATETIME CHAR(14),
ATMLABEL CHAR(20) NOT NULL,
SERIALNO CHAR(10) NOT NULL,
CARDNO CHAR(16),
VIDEOTYPE CHAR(10),
VIDEOVENDOR CHAR(20),
ASSEENO CHAR(8),
INSURANCEAMT CHAR(20),
PURCHDATETIME CHAR(14),
WDDATETIME CHAR(14),
SCRAPDATETIME CHAR(14),
ASSEEDATETIME CHAR(14),
MODULE CHAR(2),
MFEJTYPE CHAR(10),
FIXVENDOR CHAR(5),
BRANCH CHAR(10),
MONITOR CHAR(1) NOT NULL,
SECURITY CHAR(5) NOT NULL,
INSTALLTYPE CHAR(2) NOT NULL,
ATMCOST CHAR(20) NOT NULL,
FLAG CHAR(2),
SNA_FLAG CHAR(1),
ENABLE_FLAG CHAR(1),
MEMO CHAR(512),
MMEMO CHAR(160),
MODIFYDATETIME CHAR(14),
MODIFYUSER CHAR(10),
ATM_TYPE CHAR(1),
F5_VIP1 CHAR(15),
F5_VIP2 CHAR(15),
F5_VIP3 CHAR(15),
F5_VIP4 CHAR(15),
F5_VIP5 CHAR(15),
F5_VIP6 CHAR(15)
) ;


